// Outlines the wordmark from Instrument Sans 500 into src/brand/wordmark-glyphs.ts:
// `npm run brand:glyphs`. Glyphs are spaced evenly so the word spans WORD.length, the way the
// wordmark has always been set, and drawn as paths so every renderer shows the same shapes.
import { readFileSync, writeFileSync } from 'node:fs'
import opentype from 'opentype.js'
import { WORD } from '../src/brand/geometry.ts'

const FONT = 'node_modules/@fontsource/instrument-sans/files/instrument-sans-latin-500-normal.woff'
const TEXT = 'lowline'

const buf = readFileSync(FONT)
const font = opentype.parse(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength))
const scale = WORD.size / font.unitsPerEm
// One glyph per letter: "lowline" has no ligatures, so shaping would change nothing.
const glyphs = [...TEXT].map((ch) => font.charToGlyph(ch))
const advances: number[] = glyphs.map((g: any, i: number) => {
  const kern = i < glyphs.length - 1 ? font.getKerningValue(g, glyphs[i + 1]) : 0
  return (g.advanceWidth + kern) * scale
})
const natural = advances.reduce((a, b) => a + b, 0)
const extra = (WORD.length - natural) / (glyphs.length - 1)
const round = (n: number) => Math.round(n * 100) / 100

let x = WORD.x
const out = glyphs.map((g: any, i: number) => {
  const d = g.getPath(0, WORD.baseline, WORD.size).toPathData(2)
  const last = i === glyphs.length - 1
  const entry = { char: TEXT[i], x: round(x), advance: round(last ? WORD.x + WORD.length - x : advances[i] + extra), d }
  x += advances[i] + extra
  return entry
})

writeFileSync(
  'src/brand/wordmark-glyphs.ts',
  `// Generated by scripts/brand-glyphs.ts — do not edit. Each path is drawn at x = 0; place it at its x.\n\n` +
    `export interface Glyph {\n  char: string\n  x: number\n  advance: number\n  d: string\n}\n\n` +
    `export const WORDMARK_GLYPHS: readonly Glyph[] = ${JSON.stringify(out, null, 2)}\n`,
)
console.log(`wrote ${out.length} glyphs, extra spacing ${extra.toFixed(2)}`)
